### ISSUE TITLE
Light variant

### ISSUE THREAD

**Issue by agnipau** [barjoio/anirak#1]
Do you have any plans to make a light variant of this theme?
I love this theme but when I happen to be in the sun with the laptop a light theme is more readable.

**Comment by barjoco** [comment]
I'm glad you enjoy the theme and thanks for your suggestion. I don't have plans to make a light variant any time soon. It would be quite a lot of work to produce, since the whole UI is based around dark colours, as well as the syntax highlighting.

I'm not against the idea though. I plan to produce Anirak themes for other applications - sublime, atom, vim, firefox, etc., so it's quite possible that a light variant will emerge at some point.

**Comment by barjoio** [comment]
A light variant has now been introduced! It can be seen in the newest release.
